import React from "react";
import { ReactNode } from "react";

export const metadata = {
  title: "Services WebOrbit",
  description: "Generated by create next app",
};


const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <div>
      <main>{children}</main>
    </div>
  );
};

export default Layout;
